"""Initial revision

Revision ID: 4d0e71fcfbf5
Revises: 968d09417a01
Create Date: 2025-08-10 10:53:42.876847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d0e71fcfbf5'
down_revision: Union[str, None] = '968d09417a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.Text(), nullable=False))
    op.add_column('orders', sa.Column('user_name', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('fio', sa.Text(), nullable=False))
    op.add_column('orders', sa.Column('product_id', sa.Text(), nullable=False))
    op.add_column('orders', sa.Column('product_name', sa.Text(), nullable=False))
    op.add_column('orders', sa.Column('product_size', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('photo_confirm', sa.Text(), nullable=False))
    op.add_column('orders', sa.Column('confirmed', sa.Boolean(), nullable=False))
    op.add_column('orders', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('orders', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'confirmed')
    op.drop_column('orders', 'photo_confirm')
    op.drop_column('orders', 'price')
    op.drop_column('orders', 'product_size')
    op.drop_column('orders', 'product_name')
    op.drop_column('orders', 'product_id')
    op.drop_column('orders', 'fio')
    op.drop_column('orders', 'user_name')
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###
