"""Initial revision

Revision ID: 5679947802a8
Revises: 1abac9e96076
Create Date: 2025-03-12 18:03:06.339022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5679947802a8'
down_revision: Union[str, None] = '1abac9e96076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('photo_confirm', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'photo_confirm')
    # ### end Alembic commands ###
