"""Initial revision

Revision ID: 87da6db6015c
Revises: 4d0e71fcfbf5
Create Date: 2025-08-10 12:45:44.155170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87da6db6015c'
down_revision: Union[str, None] = '4d0e71fcfbf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_methotd', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_methotd')
    # ### end Alembic commands ###
